/** Famous destinations for the hero marquee — worldwide incl. India */
export const DESTINATIONS = [
  // Europe
  "Paris",
  "London",
  "Rome",
  "Barcelona",
  "Amsterdam",
  "Venice",
  "Prague",
  "Santorini",
  "Swiss Alps",
  "Amalfi Coast",
  "Lisbon",
  "Dubrovnik",
  "Reykjavik",
  "Edinburgh",
  "Vienna",
  "Florence",
  "Copenhagen",
  "Norwegian Fjords",
  "Lake Como",
  "Scottish Highlands",
  "Cappadocia",
  // Asia & Pacific
  "Kyoto",
  "Tokyo",
  "Bali",
  "Maldives",
  "Dubai",
  "Singapore",
  "Hong Kong",
  "Seoul",
  "Bangkok",
  "Hanoi",
  "Siem Reap",
  "Petra",
  "Istanbul",
  "Sydney",
  "Queenstown",
  "Great Barrier Reef",
  "Bora Bora",
  // India
  "Taj Mahal",
  "Jaipur",
  "Goa",
  "Kerala",
  "Mumbai",
  "Delhi",
  "Varanasi",
  "Udaipur",
  "Ladakh",
  "Rishikesh",
  "Hampi",
  "Amritsar",
  // Americas
  "New York",
  "San Francisco",
  "Rio de Janeiro",
  "Buenos Aires",
  "Machu Picchu",
  "Patagonia",
  "Banff",
  "Havana",
  "Mexico City",
  "Cartagena",
  "Grand Canyon",
  "Yellowstone",
  "Niagara Falls",
  // Africa & Middle East
  "Marrakech",
  "Cape Town",
  "Serengeti",
  "Cairo",
  "Zanzibar",
  "Sahara Desert",
  // Wonders & wild
  "Galápagos",
  "Antarctica",
] as const;

export type Destination = (typeof DESTINATIONS)[number];
